run:
  dataset: oulad
  rounds: 50

datasets:
  oulad:
    paths:
      base_dir: data/oulad-processed
      train: train.csv
      val: val.csv
      test: test.csv
      side_information_users: side_information_users.csv
      side_information_items: side_information_items.csv

    # interactions produced by the preprocessing already include a timestamp column
    interactions:
      timestamp: true

    # === Side-information schema (matches the preprocessing outputs) ===
    users:
      categorical: [
        gender,
        region,
        highest_education,
        imd_band,
        age_band,
        disability,
        final_result
      ]
      numeric: [
        num_of_prev_attempts,
        studied_credits,
        total_clicks,
        activity_span_days,
        activity_velocity,
        mean_success,
        decayed_success,
        recent_success_4w,
        recent_clicks_4w,
        mean_clicks_per_event,
        std_clicks_per_event,
        avg_inter_event_days
      ]

    items:
      categorical: [
        activity_type,
        code_module,
        code_presentation
      ]
      numeric: [
        week_from,             # numeric offset (from VLE week)
        duration,              # week_to - week_from
        avg_clicks,            # average clicks
        click_velocity,        # clicks per week in window
        difficulty,            # historical difficulty
        decayed_clicks,        # recency-weighted clicks
        decayed_success,       # recency-weighted success
        recent_clicks_4w,      # clicks in last 4 weeks
        recent_success_4w      # success rate last 4 weeks
      ]

    # === Sanitization (used by the orchestrator via names → one-hots) ===
    sensitive:
      users:
        # strong identifiers / protected attributes
        categoricals: [region, age_band, disability, gender, imd_band]
        numerics: []   # keep as [] unless you decide to mask studied_credits, etc.
      items:
        # generally none for OULAD; enable "code_presentation" here for very strong mode
        categoricals: []
        numerics: []

    # === Optional difficulty shaping used by seeding / ZPD band ===
    difficulty:
      mode: compute         # compute from logs (fallback to 0.5 if missing)
      halflife_days: 45     # recency decay on click/correct signals
